In [3]:
import pandas as pd

# Define o nome do arquivo que você baixou
# (Renomeie aqui se você deu um nome diferente ao seu arquivo)
file_path = 'proxy_transactions.csv' 

try:
    # Carrega o CSV para uma tabela (DataFrame) do pandas
    df = pd.read_csv(file_path)
    
    print(f"Dataset do Proxy carregado com sucesso!")
    print(f"Total de {len(df)} transações históricas para análise.")
    print("-------------------------------------------")
    
    # ---------------- Análise Rápida ----------------
    
    # 1. Quais são as interações mais comuns?
    print("\n--- Frequência dos Métodos Chamados ---")
    print(df['Method'].value_counts().head(10))
    
    # 2. Quem são os maiores 'jogadores'?
    print("\n--- Top 10 Endereços que Mais Interagiram ---")
    print(df['From'].value_counts().head(10))
    
    # 3. Vamos ver as 5 primeiras linhas para ter uma ideia dos dados
    print("\n--- Amostra dos Dados (Primeiras 5 Linhas) ---")
    display(df.head())
    
except FileNotFoundError:
    print(f"--- ERRO: Arquivo '{file_path}' não encontrado! ---")
    print("Por favor, verifique se o arquivo CSV está na mesma pasta que este notebook.")

Dataset do Proxy carregado com sucesso!
Total de 5000 transações históricas para análise.
-------------------------------------------

--- Frequência dos Métodos Chamados ---
Method
Send    5000
Name: count, dtype: int64

--- Top 10 Endereços que Mais Interagiram ---
From
0x6594f15dc6f9ad9a059af5e4a09f762446dd4474    161
0x8204af167c94dabc7ee9597e967eae1f9066ffa7    152
0x57850a559b642ce3da32a7ea9c19736a111f9758    127
0xe048282234a55924ccda94ae22e5fca79917504e    119
0xe5c4a0a12af3b43939a1eaa2fde60402e31b8ecc    118
0x108f2e0757705031a62f8ceb76001255d8f4db2d    116
0x99be2c2c201c328c3a4163bf31aa064673d6afa2    114
0x9773b33f8e36ab5c61501f01216739bf182416b6    114
0xffd2c5227af7667940acdbea57efd66adc1e1e6f    111
0x3f6392fc734c69888bc67c0160541d45a0e53412    109
Name: count, dtype: int64

--- Amostra dos Dados (Primeiras 5 Linhas) ---

,Transaction Hash,Blockno,UnixTimestamp,DateTime (UTC),From,To,ContractAddress,Value_IN(ETH),Value_OUT(ETH),CurrentValue @ $0/Eth,TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,Status,ErrCode,Method
0,0xe3e0649f7b70d03aa49e8f97e782c4cec38546d0f179...,8449777,1748736000,2025-06-01 00:00:00,0xc43497d9566193c37b16bf17d1bdb2b403ff450c,0x5fbe74a283f7954f10aa04c2edf55578811aeb03,NaN,0,0,0,0.000202,0,NaN,NaN,NaN,Send
1,0x4072bacb65a90e293b6fc0a842f6ac732e6e04e37d5c...,8449777,1748736000,2025-06-01 00:00:00,0x157867eee328bc6b0a2fa132db19b49b5660e370,0x5fbe74a283f7954f10aa04c2edf55578811aeb03,NaN,0,0,0,0.000221,0,NaN,NaN,NaN,Send
2,0xd994f29d8b7640815937945310b08ac98fe453b4ade1...,8449777,1748736000,2025-06-01 00:00:00,0x4bd970a520dead065877eaca7605065e5d678853,0x5fbe74a283f7954f10aa04c2edf55578811aeb03,NaN,0,0,0,0.000221,0,NaN,NaN,NaN,Send
3,0xb0eb945227d30078b72ac2aa553af2ad87d5878a381d...,8449777,1748736000,2025-06-01 00:00:00,0x4063889e1de1c6153bf3cf4d7ebde88ef58b7984,0x5fbe74a283f7954f10aa04c2edf55578811aeb03,NaN,0,0,0,0.000221,0,NaN,NaN,NaN,Send
4,0x9e6f7c2a5a9b47ee79aa4ec5b0851d8e6ca56f19451a...,8449777,1748736000,2025-06-01 00:00:00,0x0259a9427db645da006f5fada5850c4050b54cb5,0x5fbe74a283f7954f10aa04c2edf55578811aeb03,NaN,0,0,0,0.000221,0,NaN,NaN,NaN,Send